### ISSUE TITLE
Yeni Dil Eklenme İsteği

### ISSUE THREAD

**Issue by ilbailba** [omerayyildiz/dotfiles#1]
Merhaba Ömer YILDIZ. İlk olarak çok güzel bir kılavuz olmuş. Gerçekten büyük bir işçilik var. Fakat bir isteğim olacaktı. Bu projeye 2. bir dil daha eklenebilir mi? (türkçe :) ) teşekkürler.

**Comment by omerayyildiz** [comment]
Mac'imi İngilizce kullandığım için bu ayarların Türkçe karşılığını tam bilmiyorum. Ama şahsen bu repo için de gerek duymuyorum.
